version: "3.9"
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: docker/locallibrary/Dockerfile
    environment:
      - DB_HOST=DB
      - WEB_PORT=8000
    networks:
      - webnet
    ports:
      - "8000:8000"

  db:
    container_name: db
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - webnet
    expose:
      - 5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'dev_db'

volumes:
  db-data:
networks:
  webnet: